import { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    name: 'Жилищна сграда А1',
    location: 'София, Младост',
    active: true,
    podObekti: [
      {
        id: 'fasada-iztok',
        name: 'Фасада Изток',
        smr: [
          {
            id: 's1',
            name: 'Топлоизолация',
            active: true,
            progress: 65,
            brigade: 'Бригада Иванов',
            unit: 'm2',
            quantity: 400,
            done: 260,
            pricePerUnit: 18,
            totalValue: 7200,
            note: 'EPS 10cm плочи',
            updates: [
              {
                id: 'u1',
                done: 100,
                note: 'Първа седмица',
                timestamp: '2025-04-01T09:00:00Z',
              },
              {
                id: 'u2',
                done: 260,
                note: 'След празниците',
                timestamp: '2025-04-14T10:30:00Z',
              },
            ],
          },
          {
            id: 's2',
            name: 'Мазилка',
            active: true,
            progress: 30,
            brigade: 'Бригада Петров',
            unit: 'm2',
            quantity: 400,
            done: 120,
            pricePerUnit: 12,
            totalValue: 4800,
            note: '',
            updates: [
              {
                id: 'u3',
                done: 120,
                note: '',
                timestamp: '2025-04-10T08:00:00Z',
              },
            ],
          },
          {
            id: 's3',
            name: 'Шпакловане',
            active: false,
            progress: 100,
            brigade: 'Бригада Иванов',
            unit: 'm2',
            quantity: 200,
            done: 200,
            pricePerUnit: 8,
            totalValue: 1600,
            note: 'Завършено преди срока',
            updates: [
              {
                id: 'u4',
                done: 200,
                note: 'Завършено',
                timestamp: '2025-03-20T14:00:00Z',
              },
            ],
          },
        ],
      },
      {
        id: 'fasada-zapad',
        name: 'Фасада Запад',
        smr: [
          {
            id: 's4',
            name: 'Топлоизолация',
            active: true,
            progress: 20,
            brigade: 'Бригада Петров',
            unit: 'm2',
            quantity: 300,
            done: 60,
            pricePerUnit: 18,
            totalValue: 5400,
            note: '',
            updates: [
              {
                id: 'u5',
                done: 60,
                note: '',
                timestamp: '2025-04-12T09:00:00Z',
              },
            ],
          },
          {
            id: 's5',
            name: 'Рязане желяза',
            active: false,
            progress: 100,
            brigade: 'Бригада Димов',
            unit: 'м',
            quantity: 150,
            done: 150,
            pricePerUnit: 5,
            totalValue: 750,
            note: '',
            updates: [],
          },
        ],
      },
      {
        id: 'fasada-sever',
        name: 'Фасада Север',
        smr: [
          {
            id: 's6',
            name: 'Мазилка',
            active: true,
            progress: 10,
            brigade: 'Бригада Димов',
            unit: 'm2',
            quantity: 350,
            done: 35,
            pricePerUnit: 12,
            totalValue: 4200,
            note: '',
            updates: [],
          },
          {
            id: 's7',
            name: 'Шпакловане',
            active: true,
            progress: 45,
            brigade: 'Бригада Иванов',
            unit: 'm2',
            quantity: 350,
            done: 157,
            pricePerUnit: 8,
            totalValue: 2800,
            note: '',
            updates: [],
          },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Офис комплекс Б',
    location: 'Пловдив, Центъра',
    active: true,
    podObekti: [
      {
        id: 'etaj-1',
        name: 'Етаж 1',
        smr: [
          {
            id: 's8',
            name: 'Замазка',
            active: true,
            progress: 80,
            brigade: 'Бригада Петров',
            unit: 'm2',
            quantity: 500,
            done: 400,
            pricePerUnit: 10,
            totalValue: 5000,
            note: '',
            updates: [],
          },
          {
            id: 's9',
            name: 'Електро',
            active: true,
            progress: 55,
            brigade: 'Бригада Димов',
            unit: 'бр',
            quantity: 80,
            done: 44,
            pricePerUnit: 45,
            totalValue: 3600,
            note: 'Ел. табла + контакти',
            updates: [],
          },
          {
            id: 's10',
            name: 'Шпакловане',
            active: false,
            progress: 100,
            brigade: 'Бригада Иванов',
            unit: 'm2',
            quantity: 500,
            done: 500,
            pricePerUnit: 8,
            totalValue: 4000,
            note: '',
            updates: [],
          },
        ],
      },
      {
        id: 'etaj-2',
        name: 'Етаж 2',
        smr: [
          {
            id: 's11',
            name: 'Замазка',
            active: false,
            progress: 100,
            brigade: 'Бригада Петров',
            unit: 'm2',
            quantity: 500,
            done: 500,
            pricePerUnit: 10,
            totalValue: 5000,
            note: '',
            updates: [],
          },
          {
            id: 's12',
            name: 'Шпакловане',
            active: true,
            progress: 15,
            brigade: 'Бригада Иванов',
            unit: 'm2',
            quantity: 500,
            done: 75,
            pricePerUnit: 8,
            totalValue: 4000,
            note: '',
            updates: [],
          },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Вила Морска',
    location: 'Варна, к.к. Св. Св.',
    active: true,
    podObekti: [
      {
        id: 'sekciq-a',
        name: 'Секция А',
        smr: [
          {
            id: 's13',
            name: 'Мазилка',
            active: true,
            progress: 50,
            brigade: 'Бригада Димов',
            unit: 'm2',
            quantity: 200,
            done: 100,
            pricePerUnit: 12,
            totalValue: 2400,
            note: '',
            updates: [],
          },
          {
            id: 's14',
            name: 'Топлоизолация',
            active: true,
            progress: 70,
            brigade: 'Бригада Петров',
            unit: 'm2',
            quantity: 200,
            done: 140,
            pricePerUnit: 18,
            totalValue: 3600,
            note: '',
            updates: [],
          },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Склад Логистика',
    location: 'Русе, Индустриална',
    active: false,
    podObekti: [],
  },
  {
    id: '5',
    name: 'Хотел Планински',
    location: 'Банско, Центъра',
    active: false,
    podObekti: [],
  },
];

export function getProject(id: string) {
  return projects.find((p) => p.id === id) ?? null;
}

export function getPodObekt(projectId: string, podId: string) {
  const project = getProject(projectId);
  return project?.podObekti.find((p) => p.id === podId) ?? null;
}
